#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VENDOR=pandigital
DEVICE=smdk6410

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__VENDOR__/$VENDOR/g > ../../../vendor/$VENDOR/$DEVICE/$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__VENDOR__/__DEVICE__/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \\
    vendor/pandigital/__DEVICE__/proprietary/libdvm.so:system/lib/libdvm.so

# Standard blobs necessary for __DEVICE__
PRODUCT_COPY_FILES += \\
        vendor/pandigital/__DEVICE__/proprietary/libdvm.so:system/lib/libdvm.so \\
        vendor/pandigital/__DEVICE__/proprietary/libaudio.so:system/lib/libaudio.so 
 

# __VENDOR__ blobs for __DEVICE__
PRODUCT_COPY_FILES += \\
	vendor/pandigital/__DEVICE__/proprietary/dhcpcd.conf:system/etc/dhcpcd/dhcpcd.conf \\
	vendor/pandigital/__DEVICE__/proprietary/asound.conf:system/etc/asound.conf

# Framework files for __DEVICE__
PRODUCT_COPY_FILES += \\


# EGL files for __DEVICE__
PRODUCT_COPY_FILES += \\


# Permission files for __DEVICE__
PRODUCT_COPY_FILES += \\


# HW libs for __DEVICE__
PRODUCT_COPY_FILES += \\
    vendor/pandigital/__DEVICE__/proprietary/copybit.smdk6410.so:system/lib/hw/copybit.smdk6410.so \\
    vendor/pandigital/__DEVICE__/proprietary/gralloc.smdk6410.so:system/lib/hw/gralloc.smdk6410.so \\
    vendor/pandigital/__DEVICE__/proprietary/lights.smdk6410.so:system/lib/hw/lights.smdk6410.so

# Keychar files for __DEVICE__
PRODUCT_COPY_FILES += \\
    vendor/__VENDOR__/__DEVICE__/proprietary/gpio-keys.kcm.bin:system/usr/keychars/gpio-keys.kcm.bin

# bin files for __DEVICE__
PRODUCT_COPY_FILES += \\
 	vendor/pandigital/__DEVICE__/proprietary/dhcpcd.sh:system/bin/dhcpcd.sh \\
	vendor/pandigital/__DEVICE__/proprietary/filecheck.sh:system/bin/filecheck.sh \\
	vendor/pandigital/__DEVICE__/proprietary/loadWiFi.sh:system/bin/loadWiFi.sh \\
	vendor/pandigital/__DEVICE__/proprietary/wpa_supplicant.sh :system/bin/wpa_supplicant.sh \\
	vendor/pandigital/__DEVICE__/proprietary/liwconfig:system/bin/iwconfig \\
	vendor/pandigital/__DEVICE__/proprietary/iwevent:system/bin/iwevent \\
	vendor/pandigital/__DEVICE__/proprietary/iwgetid:system/bin/iwgetid \\
	vendor/pandigital/__DEVICE__/proprietary/iwlist:system/bin/iwlist 
	vendor/pandigital/__DEVICE__/proprietary/iwpriv:system/bin/iwpriv \\
	vendor/pandigital/__DEVICE__/proprietary/iwspy:system/bin/iwspy \\
	vendor/pandigital/__DEVICE__/proprietary/checkfile:system/bin/checkfile

# wifi/bt files for __DEVICE__
PRODUCT_COPY_FILES += \\
	vendor/pandigital/__DEVICE__/proprietary/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \\
	vendor/pandigital/__DEVICE__/proprietary/RT2870STA.dat:system/etc/Wireless/RT2870STA/RT2870STA.dat

# IME files
PRODUCT_COPY_FILES += \\

EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__VENDOR__/$VENDOR/g > ../../../vendor/$VENDOR/$DEVICE/$DEVICE-vendor.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__VENDOR__/__DEVICE__/setup-makefiles.sh

# Live wallpaper packages
PRODUCT_PACKAGES := \\


# Publish that we support the live wallpaper feature.
PRODUCT_COPY_FILES += \\

# Pick up overlay for features that depend on non-open-source files
DEVICE_PACKAGE_OVERLAYS := vendor/__VENDOR__/__DEVICE__/overlay

\$(call inherit-product, vendor/__VENDOR__/__DEVICE__/__DEVICE__-vendor-blobs.mk)
EOF

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__VENDOR__/$VENDOR/g > ../../../vendor/$VENDOR/$DEVICE/BoardConfigVendor.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/__VENDOR__/__DEVICE__/setup-makefiles.sh

#BOARD_GPS_LIBRARIES := libgps

#USE_CAMERA_STUB := false
EOF

mkdir -p ../../../vendor/$VENDOR/$DEVICE/overlay/packages/apps/Launcher2/res/layout
(cat << EOF) | sed s/__DEVICE__/$DEVICE/g | sed s/__VENDOR__/$VENDOR/g > ../../../vendor/$VENDOR/$DEVICE/overlay/packages/apps/Launcher2/res/layout/all_apps.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (C) 2010 The Android Open Source Project

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->

<!-- This file is generated by device/__VENDOR__/__DEVICE__/setup-makefiles.sh -->

<!-- switch to all_apps_3d on devices that support RenderScript -->
<merge xmlns:android="http://schemas.android.com/apk/res/android">
    <include layout="@layout/all_apps_3d" />
</merge>
EOF
