#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


DEVICE=smdk6410

mkdir -p ../../../vendor/pandigital/$DEVICE/proprietary/ 
unzip -j -o ../../../${DEVICE}_update.zip system/lib/hw/copybit.smdk6410.so system/lib/hw/gralloc.smdk6410.so system/lib/hw/lights.smdk6410.so system/usr/keychars/gpio-keys.kcm.bin system/bin/dhcpcd.sh system/bin/filecheck.sh system/bin/loadWiFi.sh system/bin/wpa_supplicant.sh system/bin/iwconfig system/bin/iwevent system/bin/iwgetid system/bin/iwlist system/bin/iwpriv system/bin/iwspy system/bin/checkfile system/bin/autobl system/etc/wifi/wpa_supplicant.conf system/etc/Wireless/RT2870STA/RT2870STA.dat system/etc/dhcpcd/dhcpcd.conf system/etc/asound.conf system/etc/vold.conf -d ../../../vendor/pandigital/$DEVICE/proprietary

(cat << EOF) | sed s/__DEVICE__/$DEVICE/g > ../../../vendor/pandigital/$DEVICE/device_$DEVICE-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pandigital/__DEVICE__/extract-files.sh

PRODUCT_COPY_FILES := \\

PRODUCT_COPY_FILES += \\

EOF

./setup-makefiles.sh
